apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/ebanking-frontend
        ports:
        - containerPort: 4200
        volumeMounts:
        - name: frontend-volume
          mountPath: /app
      volumes:
      - name: frontend-volume
        hostPath:
          path: /path/to/your/frontend/code
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer
